from enum import StrEnum


class UserRole(StrEnum):
    REQUESTER = "REQUESTER"
    APPROVER = "APPROVER"
    SYSTEM_ADMIN = "SYSTEM_ADMIN"


class ApplicantType(StrEnum):
    STUDENT = "STUDENT"
    OTHER = "OTHER"


class EvidenceTiming(StrEnum):
    PRE = "PRE"
    POST = "POST"


class EvidenceRequirementLevel(StrEnum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"


class EvidenceSubmissionStatus(StrEnum):
    MISSING = "MISSING"
    SUBMITTED = "SUBMITTED"


class ApproverType(StrEnum):
    SLACK_USER = "SLACK_USER"
    DEPARTMENT_ROLE = "DEPARTMENT_ROLE"


class ApprovalPolicy(StrEnum):
    ANY = "ANY"


class ApprovalStepStatus(StrEnum):
    WAITING = "WAITING"
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    REJECTED = "REJECTED"


class RequestStatus(StrEnum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    IN_APPROVAL = "IN_APPROVAL"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    REJECTED = "REJECTED"
    APPROVED = "APPROVED"
    APPROVED_PENDING_POST_EVIDENCE = "APPROVED_PENDING_POST_EVIDENCE"
    COMPLETED = "COMPLETED"


class AuditEventType(StrEnum):
    REQUEST_CREATED = "REQUEST_CREATED"
    REQUEST_SUBMITTED = "REQUEST_SUBMITTED"
    EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED"
    APPROVAL_STEP_APPROVED = "APPROVAL_STEP_APPROVED"
    CHANGES_REQUESTED = "CHANGES_REQUESTED"
    REQUEST_RESUBMITTED = "REQUEST_RESUBMITTED"
    REQUEST_REJECTED = "REQUEST_REJECTED"
    POST_EVIDENCE_SUBMITTED = "POST_EVIDENCE_SUBMITTED"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
